<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE DATA
	[
		<!ELEMENT DATA (PRINTER)*>
		<!ELEMENT PRINTER (ID, NAME, MODEL, DEPARTMENT, IPV4, MAC, SERIAL, INVENTARY)>
    <!ATTLIST PRINTER ID CDATA #REQUIRED>
		<!ELEMENT NAME (#PCDATA)>
		<!ELEMENT MODEL (#PCDATA)>
		<!ELEMENT DEPARTMENT (#PCDATA)>
		<!ELEMENT IPV4 (#PCDATA)>
		<!ELEMENT MAC (#PCDATA)>
		<!ELEMENT SERIAL (#PCDATA)>
		<!ELEMENT INVENTARY (#PCDATA)>
	]
>
<!--File name: printerList.xml -->
<DATA>
  <PRINTER id="0">
    <NAME></NAME>
    <MODEL>HP LaserJet P4515</MODEL>
    <DEPARTMENT>Dear </DEPARTMENT>
    <IPV4>192.168.176.50</IPV4>
    <MAC>00:23:7D:89:AE:EE</MAC>
    <SERIAL>CNFY238450</SERIAL>
    <INVENTARY>498</INVENTARY>
  </PRINTER>
  <PRINTER id="1">
    <NAME></NAME>
	  <MODEL>HP LaserJet P4515</MODEL>
    <DEPARTMENT>Dear </DEPARTMENT>
    <IPV4>192.168.176.51</IPV4>
	  <MAC>18:A9:05:FF:10:50</MAC>
	  <SERIAL>CNFY801817</SERIAL>
	  <INVENTARY>504</INVENTARY>
  </PRINTER>
  <PRINTER id="2">
    <NAME></NAME>
    <MODEL>HP LaserJet 4350</MODEL>
    <DEPARTMENT></DEPARTMENT>
    <IPV4>192.168.176.52</IPV4>
    <MAC>00:14:38:CD:13:6B</MAC>
    <SERIAL>CNHXC47042</SERIAL>
    <INVENTARY>394</INVENTARY>
  </PRINTER>
  <PRINTER id="3">
    <NAME></NAME>
    <MODEL>HP LaserJet 4350</MODEL>
    <DEPARTMENT>Dear </DEPARTMENT>
    <IPV4>192.168.176.53</IPV4>
    <MAC>00:1E:0B:14:DF:D0</MAC>
    <SERIAL>CNHXS51910</SERIAL>
    <INVENTARY>450</INVENTARY>
  </PRINTER>
  <PRINTER id="4">
    <NAME></NAME>
    <MODEL>HP LaserJet 600 M603</MODEL>
    <DEPARTMENT>Dear </DEPARTMENT>
    <IPV4>192.168.176.54</IPV4>
    <MAC>38 EA A7 6E 5A 11</MAC>
    <SERIAL>CNCVF17096</SERIAL>
    <INVENTARY>-</INVENTARY>
  </PRINTER>
  <PRINTER id="5">
    <NAME></NAME>
    <MODEL>HP LaserJet 600 M603</MODEL>
    <DEPARTMENT>Dear </DEPARTMENT>
    <IPV4>192.168.176.55</IPV4>
    <MAC>38 EA A7 6E 3A 59</MAC>
    <SERIAL>CNCVF18195</SERIAL>
    <INVENTARY>-</INVENTARY>
  </PRINTER>
  <PRINTER id="6">
    <NAME></NAME>
    <MODEL>HP LaserJet 4350</MODEL>
    <DEPARTMENT></DEPARTMENT>
    <IPV4>192.168.176.56</IPV4>
    <MAC>00 1A 4B 2C B3 54</MAC>
    <SERIAL>CNHXR02380</SERIAL>
    <INVENTARY>424</INVENTARY>
  </PRINTER>
  <PRINTER id="7">
    <NAME></NAME>
    <MODEL>HP LaserJet 4350</MODEL>
    <DEPARTMENT></DEPARTMENT>
    <IPV4>192.168.176.57</IPV4>
    <MAC>00 14 38 D9 04 E9</MAC>
    <SERIAL>CNHXG56870</SERIAL>
    <INVENTARY>400</INVENTARY>
  </PRINTER>
  <PRINTER id="8">
    <NAME></NAME>
    <MODEL>HP LaserJet 600 M603</MODEL>
    <DEPARTMENT></DEPARTMENT>
    <IPV4>192.168.176.58</IPV4>
    <MAC>EC 9A 74 30 1A 0D</MAC>
    <SERIAL>TD01YYP</SERIAL>
    <INVENTARY>580</INVENTARY>
  </PRINTER>
</DATA>         
